namespace HastaneBilgiYonetimSistemi_HBYS_NET_Framework
{
    partial class ConfirmScreenForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ConfirmScreenForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.pictureBoxConfirmScreenMailMiddleWhite = new System.Windows.Forms.PictureBox();
            this.pictureBoxConfirmScreenMailMiddleDark = new System.Windows.Forms.PictureBox();
            this.pictureBoxConfirmScreenPasswordMiddleWhite = new System.Windows.Forms.PictureBox();
            this.pictureBoxConfirmScreenPasswordMiddleDark = new System.Windows.Forms.PictureBox();
            this.labelTitle = new System.Windows.Forms.Label();
            this.labelCodeValidityPeriod = new System.Windows.Forms.Label();
            this.btn_Buttons = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtEmailConfirmNumber1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmailConfirmNumber2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmailConfirmNumber3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmailConfirmNumber4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmailConfirmNumber5 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmailConfirmNumber6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelRepeatWantToCode = new System.Windows.Forms.Label();
            this.labelRepeatCodeWaitingTime = new System.Windows.Forms.Label();
            this.labelWrongCode = new System.Windows.Forms.Label();
            this.btn_ConfirmPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_ConfirmMail = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenMailMiddleWhite)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenMailMiddleDark)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenPasswordMiddleWhite)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenPasswordMiddleDark)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBoxConfirmScreenMailMiddleWhite
            // 
            this.pictureBoxConfirmScreenMailMiddleWhite.Image = global::HastaneBilgiYonetimSistemi_HBYS_NET_Framework.Properties.Resources.check_mailWhite;
            this.pictureBoxConfirmScreenMailMiddleWhite.Location = new System.Drawing.Point(187, 40);
            this.pictureBoxConfirmScreenMailMiddleWhite.Name = "pictureBoxConfirmScreenMailMiddleWhite";
            this.pictureBoxConfirmScreenMailMiddleWhite.Size = new System.Drawing.Size(270, 84);
            this.pictureBoxConfirmScreenMailMiddleWhite.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxConfirmScreenMailMiddleWhite.TabIndex = 0;
            this.pictureBoxConfirmScreenMailMiddleWhite.TabStop = false;
            // 
            // pictureBoxConfirmScreenMailMiddleDark
            // 
            this.pictureBoxConfirmScreenMailMiddleDark.Image = global::HastaneBilgiYonetimSistemi_HBYS_NET_Framework.Properties.Resources.check_mailDark1;
            this.pictureBoxConfirmScreenMailMiddleDark.Location = new System.Drawing.Point(187, 40);
            this.pictureBoxConfirmScreenMailMiddleDark.Name = "pictureBoxConfirmScreenMailMiddleDark";
            this.pictureBoxConfirmScreenMailMiddleDark.Size = new System.Drawing.Size(270, 84);
            this.pictureBoxConfirmScreenMailMiddleDark.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxConfirmScreenMailMiddleDark.TabIndex = 0;
            this.pictureBoxConfirmScreenMailMiddleDark.TabStop = false;
            this.pictureBoxConfirmScreenMailMiddleDark.Visible = false;
            // 
            // pictureBoxConfirmScreenPasswordMiddleWhite
            // 
            this.pictureBoxConfirmScreenPasswordMiddleWhite.Image = global::HastaneBilgiYonetimSistemi_HBYS_NET_Framework.Properties.Resources.BannerWhite;
            this.pictureBoxConfirmScreenPasswordMiddleWhite.Location = new System.Drawing.Point(187, 40);
            this.pictureBoxConfirmScreenPasswordMiddleWhite.Name = "pictureBoxConfirmScreenPasswordMiddleWhite";
            this.pictureBoxConfirmScreenPasswordMiddleWhite.Size = new System.Drawing.Size(270, 84);
            this.pictureBoxConfirmScreenPasswordMiddleWhite.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxConfirmScreenPasswordMiddleWhite.TabIndex = 0;
            this.pictureBoxConfirmScreenPasswordMiddleWhite.TabStop = false;
            this.pictureBoxConfirmScreenPasswordMiddleWhite.Visible = false;
            // 
            // pictureBoxConfirmScreenPasswordMiddleDark
            // 
            this.pictureBoxConfirmScreenPasswordMiddleDark.Image = global::HastaneBilgiYonetimSistemi_HBYS_NET_Framework.Properties.Resources.BannerDark2;
            this.pictureBoxConfirmScreenPasswordMiddleDark.Location = new System.Drawing.Point(187, 40);
            this.pictureBoxConfirmScreenPasswordMiddleDark.Name = "pictureBoxConfirmScreenPasswordMiddleDark";
            this.pictureBoxConfirmScreenPasswordMiddleDark.Size = new System.Drawing.Size(270, 84);
            this.pictureBoxConfirmScreenPasswordMiddleDark.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxConfirmScreenPasswordMiddleDark.TabIndex = 0;
            this.pictureBoxConfirmScreenPasswordMiddleDark.TabStop = false;
            this.pictureBoxConfirmScreenPasswordMiddleDark.Visible = false;
            // 
            // labelTitle
            // 
            this.labelTitle.AutoSize = true;
            this.labelTitle.Font = new System.Drawing.Font("Sans Serif Collection", 6F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelTitle.ForeColor = System.Drawing.Color.Red;
            this.labelTitle.Location = new System.Drawing.Point(98, 137);
            this.labelTitle.Name = "labelTitle";
            this.labelTitle.Size = new System.Drawing.Size(433, 24);
            this.labelTitle.TabIndex = 1;
            this.labelTitle.Text = "Lütfen e-posta adresinize gönderilen 6 haneli kodu giriniz.";
            // 
            // labelCodeValidityPeriod
            // 
            this.labelCodeValidityPeriod.AutoSize = true;
            this.labelCodeValidityPeriod.Font = new System.Drawing.Font("Calibri", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.labelCodeValidityPeriod.ForeColor = System.Drawing.Color.Gray;
            this.labelCodeValidityPeriod.Location = new System.Drawing.Point(202, 162);
            this.labelCodeValidityPeriod.Name = "labelCodeValidityPeriod";
            this.labelCodeValidityPeriod.Size = new System.Drawing.Size(237, 22);
            this.labelCodeValidityPeriod.TabIndex = 2;
            this.labelCodeValidityPeriod.Text = "Kod Geçerlilik Süresi : 5 Saniye";
            // 
            // btn_Buttons
            // 
            this.btn_Buttons.AllowAnimations = true;
            this.btn_Buttons.AllowMouseEffects = true;
            this.btn_Buttons.AllowToggling = false;
            this.btn_Buttons.AnimationSpeed = 200;
            this.btn_Buttons.AutoGenerateColors = false;
            this.btn_Buttons.AutoRoundBorders = false;
            this.btn_Buttons.AutoSizeLeftIcon = true;
            this.btn_Buttons.AutoSizeRightIcon = true;
            this.btn_Buttons.BackColor = System.Drawing.Color.Transparent;
            this.btn_Buttons.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Buttons.BackgroundImage")));
            this.btn_Buttons.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Buttons.ButtonText = "";
            this.btn_Buttons.ButtonTextMarginLeft = 0;
            this.btn_Buttons.ColorContrastOnClick = 45;
            this.btn_Buttons.ColorContrastOnHover = 45;
            this.btn_Buttons.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_Buttons.CustomizableEdges = borderEdges1;
            this.btn_Buttons.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Buttons.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.Enabled = false;
            this.btn_Buttons.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Buttons.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_Buttons.ForeColor = System.Drawing.Color.White;
            this.btn_Buttons.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Buttons.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Buttons.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Buttons.IconMarginLeft = 11;
            this.btn_Buttons.IconPadding = 10;
            this.btn_Buttons.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Buttons.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Buttons.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Buttons.IconSize = 25;
            this.btn_Buttons.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.IdleBorderRadius = 60;
            this.btn_Buttons.IdleBorderThickness = 1;
            this.btn_Buttons.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.IdleIconLeftImage = null;
            this.btn_Buttons.IdleIconRightImage = null;
            this.btn_Buttons.IndicateFocus = false;
            this.btn_Buttons.Location = new System.Drawing.Point(30, 186);
            this.btn_Buttons.Name = "btn_Buttons";
            this.btn_Buttons.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnDisabledState.BorderRadius = 60;
            this.btn_Buttons.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Buttons.OnDisabledState.BorderThickness = 1;
            this.btn_Buttons.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnDisabledState.IconLeftImage = null;
            this.btn_Buttons.OnDisabledState.IconRightImage = null;
            this.btn_Buttons.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.onHoverState.BorderRadius = 60;
            this.btn_Buttons.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Buttons.onHoverState.BorderThickness = 1;
            this.btn_Buttons.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Buttons.onHoverState.IconLeftImage = null;
            this.btn_Buttons.onHoverState.IconRightImage = null;
            this.btn_Buttons.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnIdleState.BorderRadius = 60;
            this.btn_Buttons.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Buttons.OnIdleState.BorderThickness = 1;
            this.btn_Buttons.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Buttons.OnIdleState.IconLeftImage = null;
            this.btn_Buttons.OnIdleState.IconRightImage = null;
            this.btn_Buttons.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnPressedState.BorderRadius = 60;
            this.btn_Buttons.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Buttons.OnPressedState.BorderThickness = 1;
            this.btn_Buttons.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.btn_Buttons.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Buttons.OnPressedState.IconLeftImage = null;
            this.btn_Buttons.OnPressedState.IconRightImage = null;
            this.btn_Buttons.Size = new System.Drawing.Size(575, 129);
            this.btn_Buttons.TabIndex = 3;
            this.btn_Buttons.TabStop = false;
            this.btn_Buttons.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Buttons.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Buttons.TextMarginLeft = 0;
            this.btn_Buttons.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Buttons.UseDefaultRadiusAndThickness = true;
            // 
            // txtEmailConfirmNumber1
            // 
            this.txtEmailConfirmNumber1.AcceptsReturn = false;
            this.txtEmailConfirmNumber1.AcceptsTab = false;
            this.txtEmailConfirmNumber1.AnimationSpeed = 200;
            this.txtEmailConfirmNumber1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber1.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber1.BackgroundImage")));
            this.txtEmailConfirmNumber1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber1.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber1.BorderRadius = 30;
            this.txtEmailConfirmNumber1.BorderThickness = 2;
            this.txtEmailConfirmNumber1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber1.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber1.DefaultText = "";
            this.txtEmailConfirmNumber1.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber1.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber1.HideSelection = true;
            this.txtEmailConfirmNumber1.IconLeft = null;
            this.txtEmailConfirmNumber1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber1.IconPadding = 10;
            this.txtEmailConfirmNumber1.IconRight = null;
            this.txtEmailConfirmNumber1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber1.Lines = new string[0];
            this.txtEmailConfirmNumber1.Location = new System.Drawing.Point(61, 211);
            this.txtEmailConfirmNumber1.MaxLength = 1;
            this.txtEmailConfirmNumber1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber1.Modified = false;
            this.txtEmailConfirmNumber1.Multiline = false;
            this.txtEmailConfirmNumber1.Name = "txtEmailConfirmNumber1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber1.OnIdleState = stateProperties4;
            this.txtEmailConfirmNumber1.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber1.PasswordChar = '\0';
            this.txtEmailConfirmNumber1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber1.PlaceholderText = "";
            this.txtEmailConfirmNumber1.ReadOnly = false;
            this.txtEmailConfirmNumber1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber1.SelectedText = "";
            this.txtEmailConfirmNumber1.SelectionLength = 0;
            this.txtEmailConfirmNumber1.SelectionStart = 0;
            this.txtEmailConfirmNumber1.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber1.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber1.TabIndex = 1;
            this.txtEmailConfirmNumber1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber1.TextMarginBottom = 0;
            this.txtEmailConfirmNumber1.TextMarginLeft = 3;
            this.txtEmailConfirmNumber1.TextMarginTop = 0;
            this.txtEmailConfirmNumber1.TextPlaceholder = "";
            this.txtEmailConfirmNumber1.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber1.WordWrap = true;
            this.txtEmailConfirmNumber1.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber1.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // txtEmailConfirmNumber2
            // 
            this.txtEmailConfirmNumber2.AcceptsReturn = false;
            this.txtEmailConfirmNumber2.AcceptsTab = false;
            this.txtEmailConfirmNumber2.AnimationSpeed = 200;
            this.txtEmailConfirmNumber2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber2.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber2.BackgroundImage")));
            this.txtEmailConfirmNumber2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber2.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber2.BorderRadius = 30;
            this.txtEmailConfirmNumber2.BorderThickness = 2;
            this.txtEmailConfirmNumber2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber2.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber2.DefaultText = "";
            this.txtEmailConfirmNumber2.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber2.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber2.HideSelection = true;
            this.txtEmailConfirmNumber2.IconLeft = null;
            this.txtEmailConfirmNumber2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber2.IconPadding = 10;
            this.txtEmailConfirmNumber2.IconRight = null;
            this.txtEmailConfirmNumber2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber2.Lines = new string[0];
            this.txtEmailConfirmNumber2.Location = new System.Drawing.Point(150, 211);
            this.txtEmailConfirmNumber2.MaxLength = 1;
            this.txtEmailConfirmNumber2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber2.Modified = false;
            this.txtEmailConfirmNumber2.Multiline = false;
            this.txtEmailConfirmNumber2.Name = "txtEmailConfirmNumber2";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber2.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber2.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber2.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber2.OnIdleState = stateProperties8;
            this.txtEmailConfirmNumber2.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber2.PasswordChar = '\0';
            this.txtEmailConfirmNumber2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber2.PlaceholderText = "";
            this.txtEmailConfirmNumber2.ReadOnly = false;
            this.txtEmailConfirmNumber2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber2.SelectedText = "";
            this.txtEmailConfirmNumber2.SelectionLength = 0;
            this.txtEmailConfirmNumber2.SelectionStart = 0;
            this.txtEmailConfirmNumber2.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber2.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber2.TabIndex = 2;
            this.txtEmailConfirmNumber2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber2.TextMarginBottom = 0;
            this.txtEmailConfirmNumber2.TextMarginLeft = 3;
            this.txtEmailConfirmNumber2.TextMarginTop = 0;
            this.txtEmailConfirmNumber2.TextPlaceholder = "";
            this.txtEmailConfirmNumber2.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber2.WordWrap = true;
            this.txtEmailConfirmNumber2.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber2.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // txtEmailConfirmNumber3
            // 
            this.txtEmailConfirmNumber3.AcceptsReturn = false;
            this.txtEmailConfirmNumber3.AcceptsTab = false;
            this.txtEmailConfirmNumber3.AnimationSpeed = 200;
            this.txtEmailConfirmNumber3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber3.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber3.BackgroundImage")));
            this.txtEmailConfirmNumber3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber3.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber3.BorderRadius = 30;
            this.txtEmailConfirmNumber3.BorderThickness = 2;
            this.txtEmailConfirmNumber3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber3.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber3.DefaultText = "";
            this.txtEmailConfirmNumber3.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber3.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber3.HideSelection = true;
            this.txtEmailConfirmNumber3.IconLeft = null;
            this.txtEmailConfirmNumber3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber3.IconPadding = 10;
            this.txtEmailConfirmNumber3.IconRight = null;
            this.txtEmailConfirmNumber3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber3.Lines = new string[0];
            this.txtEmailConfirmNumber3.Location = new System.Drawing.Point(239, 211);
            this.txtEmailConfirmNumber3.MaxLength = 1;
            this.txtEmailConfirmNumber3.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber3.Modified = false;
            this.txtEmailConfirmNumber3.Multiline = false;
            this.txtEmailConfirmNumber3.Name = "txtEmailConfirmNumber3";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber3.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber3.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber3.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber3.OnIdleState = stateProperties12;
            this.txtEmailConfirmNumber3.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber3.PasswordChar = '\0';
            this.txtEmailConfirmNumber3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber3.PlaceholderText = "";
            this.txtEmailConfirmNumber3.ReadOnly = false;
            this.txtEmailConfirmNumber3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber3.SelectedText = "";
            this.txtEmailConfirmNumber3.SelectionLength = 0;
            this.txtEmailConfirmNumber3.SelectionStart = 0;
            this.txtEmailConfirmNumber3.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber3.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber3.TabIndex = 3;
            this.txtEmailConfirmNumber3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber3.TextMarginBottom = 0;
            this.txtEmailConfirmNumber3.TextMarginLeft = 3;
            this.txtEmailConfirmNumber3.TextMarginTop = 0;
            this.txtEmailConfirmNumber3.TextPlaceholder = "";
            this.txtEmailConfirmNumber3.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber3.WordWrap = true;
            this.txtEmailConfirmNumber3.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber3.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // txtEmailConfirmNumber4
            // 
            this.txtEmailConfirmNumber4.AcceptsReturn = false;
            this.txtEmailConfirmNumber4.AcceptsTab = false;
            this.txtEmailConfirmNumber4.AnimationSpeed = 200;
            this.txtEmailConfirmNumber4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber4.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber4.BackgroundImage")));
            this.txtEmailConfirmNumber4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber4.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber4.BorderRadius = 30;
            this.txtEmailConfirmNumber4.BorderThickness = 2;
            this.txtEmailConfirmNumber4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber4.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber4.DefaultText = "";
            this.txtEmailConfirmNumber4.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber4.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber4.HideSelection = true;
            this.txtEmailConfirmNumber4.IconLeft = null;
            this.txtEmailConfirmNumber4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber4.IconPadding = 10;
            this.txtEmailConfirmNumber4.IconRight = null;
            this.txtEmailConfirmNumber4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber4.Lines = new string[0];
            this.txtEmailConfirmNumber4.Location = new System.Drawing.Point(327, 211);
            this.txtEmailConfirmNumber4.MaxLength = 1;
            this.txtEmailConfirmNumber4.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber4.Modified = false;
            this.txtEmailConfirmNumber4.Multiline = false;
            this.txtEmailConfirmNumber4.Name = "txtEmailConfirmNumber4";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber4.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber4.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber4.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber4.OnIdleState = stateProperties16;
            this.txtEmailConfirmNumber4.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber4.PasswordChar = '\0';
            this.txtEmailConfirmNumber4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber4.PlaceholderText = "";
            this.txtEmailConfirmNumber4.ReadOnly = false;
            this.txtEmailConfirmNumber4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber4.SelectedText = "";
            this.txtEmailConfirmNumber4.SelectionLength = 0;
            this.txtEmailConfirmNumber4.SelectionStart = 0;
            this.txtEmailConfirmNumber4.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber4.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber4.TabIndex = 4;
            this.txtEmailConfirmNumber4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber4.TextMarginBottom = 0;
            this.txtEmailConfirmNumber4.TextMarginLeft = 3;
            this.txtEmailConfirmNumber4.TextMarginTop = 0;
            this.txtEmailConfirmNumber4.TextPlaceholder = "";
            this.txtEmailConfirmNumber4.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber4.WordWrap = true;
            this.txtEmailConfirmNumber4.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber4.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // txtEmailConfirmNumber5
            // 
            this.txtEmailConfirmNumber5.AcceptsReturn = false;
            this.txtEmailConfirmNumber5.AcceptsTab = false;
            this.txtEmailConfirmNumber5.AnimationSpeed = 200;
            this.txtEmailConfirmNumber5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber5.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber5.BackgroundImage")));
            this.txtEmailConfirmNumber5.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber5.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber5.BorderRadius = 30;
            this.txtEmailConfirmNumber5.BorderThickness = 2;
            this.txtEmailConfirmNumber5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber5.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber5.DefaultText = "";
            this.txtEmailConfirmNumber5.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber5.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber5.HideSelection = true;
            this.txtEmailConfirmNumber5.IconLeft = null;
            this.txtEmailConfirmNumber5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber5.IconPadding = 10;
            this.txtEmailConfirmNumber5.IconRight = null;
            this.txtEmailConfirmNumber5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber5.Lines = new string[0];
            this.txtEmailConfirmNumber5.Location = new System.Drawing.Point(415, 211);
            this.txtEmailConfirmNumber5.MaxLength = 1;
            this.txtEmailConfirmNumber5.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber5.Modified = false;
            this.txtEmailConfirmNumber5.Multiline = false;
            this.txtEmailConfirmNumber5.Name = "txtEmailConfirmNumber5";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber5.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber5.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber5.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber5.OnIdleState = stateProperties20;
            this.txtEmailConfirmNumber5.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber5.PasswordChar = '\0';
            this.txtEmailConfirmNumber5.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber5.PlaceholderText = "";
            this.txtEmailConfirmNumber5.ReadOnly = false;
            this.txtEmailConfirmNumber5.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber5.SelectedText = "";
            this.txtEmailConfirmNumber5.SelectionLength = 0;
            this.txtEmailConfirmNumber5.SelectionStart = 0;
            this.txtEmailConfirmNumber5.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber5.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber5.TabIndex = 5;
            this.txtEmailConfirmNumber5.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber5.TextMarginBottom = 0;
            this.txtEmailConfirmNumber5.TextMarginLeft = 3;
            this.txtEmailConfirmNumber5.TextMarginTop = 0;
            this.txtEmailConfirmNumber5.TextPlaceholder = "";
            this.txtEmailConfirmNumber5.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber5.WordWrap = true;
            this.txtEmailConfirmNumber5.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber5.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // txtEmailConfirmNumber6
            // 
            this.txtEmailConfirmNumber6.AcceptsReturn = false;
            this.txtEmailConfirmNumber6.AcceptsTab = false;
            this.txtEmailConfirmNumber6.AnimationSpeed = 200;
            this.txtEmailConfirmNumber6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmailConfirmNumber6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmailConfirmNumber6.BackColor = System.Drawing.Color.Transparent;
            this.txtEmailConfirmNumber6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmailConfirmNumber6.BackgroundImage")));
            this.txtEmailConfirmNumber6.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmailConfirmNumber6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmailConfirmNumber6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmailConfirmNumber6.BorderColorIdle = System.Drawing.Color.White;
            this.txtEmailConfirmNumber6.BorderRadius = 30;
            this.txtEmailConfirmNumber6.BorderThickness = 2;
            this.txtEmailConfirmNumber6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmailConfirmNumber6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber6.DefaultFont = new System.Drawing.Font("Roboto", 34.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtEmailConfirmNumber6.DefaultText = "";
            this.txtEmailConfirmNumber6.FillColor = System.Drawing.Color.White;
            this.txtEmailConfirmNumber6.ForeColor = System.Drawing.Color.Black;
            this.txtEmailConfirmNumber6.HideSelection = true;
            this.txtEmailConfirmNumber6.IconLeft = null;
            this.txtEmailConfirmNumber6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber6.IconPadding = 10;
            this.txtEmailConfirmNumber6.IconRight = null;
            this.txtEmailConfirmNumber6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmailConfirmNumber6.Lines = new string[0];
            this.txtEmailConfirmNumber6.Location = new System.Drawing.Point(504, 211);
            this.txtEmailConfirmNumber6.MaxLength = 1;
            this.txtEmailConfirmNumber6.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmailConfirmNumber6.Modified = false;
            this.txtEmailConfirmNumber6.Multiline = false;
            this.txtEmailConfirmNumber6.Name = "txtEmailConfirmNumber6";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber6.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmailConfirmNumber6.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber6.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmailConfirmNumber6.OnIdleState = stateProperties24;
            this.txtEmailConfirmNumber6.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmailConfirmNumber6.PasswordChar = '\0';
            this.txtEmailConfirmNumber6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmailConfirmNumber6.PlaceholderText = "";
            this.txtEmailConfirmNumber6.ReadOnly = false;
            this.txtEmailConfirmNumber6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmailConfirmNumber6.SelectedText = "";
            this.txtEmailConfirmNumber6.SelectionLength = 0;
            this.txtEmailConfirmNumber6.SelectionStart = 0;
            this.txtEmailConfirmNumber6.ShortcutsEnabled = true;
            this.txtEmailConfirmNumber6.Size = new System.Drawing.Size(64, 98);
            this.txtEmailConfirmNumber6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmailConfirmNumber6.TabIndex = 6;
            this.txtEmailConfirmNumber6.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtEmailConfirmNumber6.TextMarginBottom = 0;
            this.txtEmailConfirmNumber6.TextMarginLeft = 3;
            this.txtEmailConfirmNumber6.TextMarginTop = 0;
            this.txtEmailConfirmNumber6.TextPlaceholder = "";
            this.txtEmailConfirmNumber6.UseSystemPasswordChar = false;
            this.txtEmailConfirmNumber6.WordWrap = true;
            this.txtEmailConfirmNumber6.TextChange += new System.EventHandler(this.TextBox_TextChanged);
            this.txtEmailConfirmNumber6.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.Number_KeyPress);
            // 
            // labelRepeatWantToCode
            // 
            this.labelRepeatWantToCode.AutoSize = true;
            this.labelRepeatWantToCode.Cursor = System.Windows.Forms.Cursors.Hand;
            this.labelRepeatWantToCode.Font = new System.Drawing.Font("Roboto", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.labelRepeatWantToCode.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(160)))), ((int)(((byte)(243)))));
            this.labelRepeatWantToCode.Location = new System.Drawing.Point(468, 331);
            this.labelRepeatWantToCode.Name = "labelRepeatWantToCode";
            this.labelRepeatWantToCode.Size = new System.Drawing.Size(109, 18);
            this.labelRepeatWantToCode.TabIndex = 7;
            this.labelRepeatWantToCode.Text = "Tekrar Kod İste";
            this.labelRepeatWantToCode.Click += new System.EventHandler(this.labelRepeatWantToCode_Click);
            // 
            // labelRepeatCodeWaitingTime
            // 
            this.labelRepeatCodeWaitingTime.AutoSize = true;
            this.labelRepeatCodeWaitingTime.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112)))));
            this.labelRepeatCodeWaitingTime.Location = new System.Drawing.Point(450, 353);
            this.labelRepeatCodeWaitingTime.Name = "labelRepeatCodeWaitingTime";
            this.labelRepeatCodeWaitingTime.Size = new System.Drawing.Size(150, 32);
            this.labelRepeatCodeWaitingTime.TabIndex = 8;
            this.labelRepeatCodeWaitingTime.Text = "Yeniden Kod İstemek İçin\r\nKalan Süre :\r\n";
            this.labelRepeatCodeWaitingTime.Visible = false;
            // 
            // labelWrongCode
            // 
            this.labelWrongCode.AutoSize = true;
            this.labelWrongCode.Font = new System.Drawing.Font("Calibri", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.labelWrongCode.ForeColor = System.Drawing.Color.Red;
            this.labelWrongCode.Location = new System.Drawing.Point(237, 349);
            this.labelWrongCode.Name = "labelWrongCode";
            this.labelWrongCode.Size = new System.Drawing.Size(104, 21);
            this.labelWrongCode.TabIndex = 9;
            this.labelWrongCode.Text = "YANLIŞ KOD !";
            this.labelWrongCode.Visible = false;
            // 
            // btn_ConfirmPassword
            // 
            this.btn_ConfirmPassword.AllowAnimations = true;
            this.btn_ConfirmPassword.AllowMouseEffects = true;
            this.btn_ConfirmPassword.AllowToggling = false;
            this.btn_ConfirmPassword.AnimationSpeed = 200;
            this.btn_ConfirmPassword.AutoGenerateColors = false;
            this.btn_ConfirmPassword.AutoRoundBorders = false;
            this.btn_ConfirmPassword.AutoSizeLeftIcon = true;
            this.btn_ConfirmPassword.AutoSizeRightIcon = true;
            this.btn_ConfirmPassword.BackColor = System.Drawing.Color.Transparent;
            this.btn_ConfirmPassword.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_ConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ConfirmPassword.BackgroundImage")));
            this.btn_ConfirmPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmPassword.ButtonText = "ONAYLA";
            this.btn_ConfirmPassword.ButtonTextMarginLeft = 0;
            this.btn_ConfirmPassword.ColorContrastOnClick = 45;
            this.btn_ConfirmPassword.ColorContrastOnHover = 45;
            this.btn_ConfirmPassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_ConfirmPassword.CustomizableEdges = borderEdges2;
            this.btn_ConfirmPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ConfirmPassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ConfirmPassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ConfirmPassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ConfirmPassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ConfirmPassword.Font = new System.Drawing.Font("Calibri", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_ConfirmPassword.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmPassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_ConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ConfirmPassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_ConfirmPassword.IconMarginLeft = 11;
            this.btn_ConfirmPassword.IconPadding = 10;
            this.btn_ConfirmPassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_ConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ConfirmPassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_ConfirmPassword.IconSize = 25;
            this.btn_ConfirmPassword.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_ConfirmPassword.IdleBorderRadius = 15;
            this.btn_ConfirmPassword.IdleBorderThickness = 1;
            this.btn_ConfirmPassword.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_ConfirmPassword.IdleIconLeftImage = null;
            this.btn_ConfirmPassword.IdleIconRightImage = null;
            this.btn_ConfirmPassword.IndicateFocus = false;
            this.btn_ConfirmPassword.Location = new System.Drawing.Point(30, 337);
            this.btn_ConfirmPassword.Name = "btn_ConfirmPassword";
            this.btn_ConfirmPassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ConfirmPassword.OnDisabledState.BorderRadius = 15;
            this.btn_ConfirmPassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmPassword.OnDisabledState.BorderThickness = 1;
            this.btn_ConfirmPassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ConfirmPassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ConfirmPassword.OnDisabledState.IconLeftImage = null;
            this.btn_ConfirmPassword.OnDisabledState.IconRightImage = null;
            this.btn_ConfirmPassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_ConfirmPassword.onHoverState.BorderRadius = 15;
            this.btn_ConfirmPassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmPassword.onHoverState.BorderThickness = 1;
            this.btn_ConfirmPassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_ConfirmPassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmPassword.onHoverState.IconLeftImage = null;
            this.btn_ConfirmPassword.onHoverState.IconRightImage = null;
            this.btn_ConfirmPassword.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_ConfirmPassword.OnIdleState.BorderRadius = 15;
            this.btn_ConfirmPassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmPassword.OnIdleState.BorderThickness = 1;
            this.btn_ConfirmPassword.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_ConfirmPassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmPassword.OnIdleState.IconLeftImage = null;
            this.btn_ConfirmPassword.OnIdleState.IconRightImage = null;
            this.btn_ConfirmPassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_ConfirmPassword.OnPressedState.BorderRadius = 15;
            this.btn_ConfirmPassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmPassword.OnPressedState.BorderThickness = 1;
            this.btn_ConfirmPassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_ConfirmPassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmPassword.OnPressedState.IconLeftImage = null;
            this.btn_ConfirmPassword.OnPressedState.IconRightImage = null;
            this.btn_ConfirmPassword.Size = new System.Drawing.Size(175, 50);
            this.btn_ConfirmPassword.TabIndex = 10;
            this.btn_ConfirmPassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ConfirmPassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_ConfirmPassword.TextMarginLeft = 0;
            this.btn_ConfirmPassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_ConfirmPassword.UseDefaultRadiusAndThickness = true;
            this.btn_ConfirmPassword.Click += new System.EventHandler(this.btn_ConfirmPassword_Click);
            // 
            // btn_ConfirmMail
            // 
            this.btn_ConfirmMail.AllowAnimations = true;
            this.btn_ConfirmMail.AllowMouseEffects = true;
            this.btn_ConfirmMail.AllowToggling = false;
            this.btn_ConfirmMail.AnimationSpeed = 200;
            this.btn_ConfirmMail.AutoGenerateColors = false;
            this.btn_ConfirmMail.AutoRoundBorders = false;
            this.btn_ConfirmMail.AutoSizeLeftIcon = true;
            this.btn_ConfirmMail.AutoSizeRightIcon = true;
            this.btn_ConfirmMail.BackColor = System.Drawing.Color.Transparent;
            this.btn_ConfirmMail.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(177)))), ((int)(((byte)(172)))));
            this.btn_ConfirmMail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ConfirmMail.BackgroundImage")));
            this.btn_ConfirmMail.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmMail.ButtonText = "E-POSTANI ONAYLA";
            this.btn_ConfirmMail.ButtonTextMarginLeft = 0;
            this.btn_ConfirmMail.ColorContrastOnClick = 45;
            this.btn_ConfirmMail.ColorContrastOnHover = 45;
            this.btn_ConfirmMail.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_ConfirmMail.CustomizableEdges = borderEdges3;
            this.btn_ConfirmMail.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ConfirmMail.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ConfirmMail.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ConfirmMail.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ConfirmMail.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ConfirmMail.Font = new System.Drawing.Font("Calibri", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_ConfirmMail.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmMail.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_ConfirmMail.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ConfirmMail.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_ConfirmMail.IconMarginLeft = 11;
            this.btn_ConfirmMail.IconPadding = 10;
            this.btn_ConfirmMail.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_ConfirmMail.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ConfirmMail.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_ConfirmMail.IconSize = 25;
            this.btn_ConfirmMail.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(177)))), ((int)(((byte)(172)))));
            this.btn_ConfirmMail.IdleBorderRadius = 15;
            this.btn_ConfirmMail.IdleBorderThickness = 1;
            this.btn_ConfirmMail.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(177)))), ((int)(((byte)(172)))));
            this.btn_ConfirmMail.IdleIconLeftImage = null;
            this.btn_ConfirmMail.IdleIconRightImage = null;
            this.btn_ConfirmMail.IndicateFocus = false;
            this.btn_ConfirmMail.Location = new System.Drawing.Point(30, 337);
            this.btn_ConfirmMail.Name = "btn_ConfirmMail";
            this.btn_ConfirmMail.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ConfirmMail.OnDisabledState.BorderRadius = 15;
            this.btn_ConfirmMail.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmMail.OnDisabledState.BorderThickness = 1;
            this.btn_ConfirmMail.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ConfirmMail.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ConfirmMail.OnDisabledState.IconLeftImage = null;
            this.btn_ConfirmMail.OnDisabledState.IconRightImage = null;
            this.btn_ConfirmMail.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(217)))), ((int)(((byte)(174)))));
            this.btn_ConfirmMail.onHoverState.BorderRadius = 15;
            this.btn_ConfirmMail.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmMail.onHoverState.BorderThickness = 1;
            this.btn_ConfirmMail.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(217)))), ((int)(((byte)(174)))));
            this.btn_ConfirmMail.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmMail.onHoverState.IconLeftImage = null;
            this.btn_ConfirmMail.onHoverState.IconRightImage = null;
            this.btn_ConfirmMail.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(177)))), ((int)(((byte)(172)))));
            this.btn_ConfirmMail.OnIdleState.BorderRadius = 15;
            this.btn_ConfirmMail.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmMail.OnIdleState.BorderThickness = 1;
            this.btn_ConfirmMail.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(177)))), ((int)(((byte)(172)))));
            this.btn_ConfirmMail.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmMail.OnIdleState.IconLeftImage = null;
            this.btn_ConfirmMail.OnIdleState.IconRightImage = null;
            this.btn_ConfirmMail.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(138)))), ((int)(((byte)(134)))));
            this.btn_ConfirmMail.OnPressedState.BorderRadius = 15;
            this.btn_ConfirmMail.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ConfirmMail.OnPressedState.BorderThickness = 1;
            this.btn_ConfirmMail.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(138)))), ((int)(((byte)(134)))));
            this.btn_ConfirmMail.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_ConfirmMail.OnPressedState.IconLeftImage = null;
            this.btn_ConfirmMail.OnPressedState.IconRightImage = null;
            this.btn_ConfirmMail.Size = new System.Drawing.Size(175, 50);
            this.btn_ConfirmMail.TabIndex = 10;
            this.btn_ConfirmMail.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ConfirmMail.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_ConfirmMail.TextMarginLeft = 0;
            this.btn_ConfirmMail.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_ConfirmMail.UseDefaultRadiusAndThickness = true;
            this.btn_ConfirmMail.Visible = false;
            this.btn_ConfirmMail.Click += new System.EventHandler(this.btn_ConfirmMail_Click);
            // 
            // ConfirmScreenForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(635, 402);
            this.Controls.Add(this.labelWrongCode);
            this.Controls.Add(this.labelRepeatCodeWaitingTime);
            this.Controls.Add(this.labelRepeatWantToCode);
            this.Controls.Add(this.txtEmailConfirmNumber6);
            this.Controls.Add(this.txtEmailConfirmNumber5);
            this.Controls.Add(this.txtEmailConfirmNumber4);
            this.Controls.Add(this.txtEmailConfirmNumber3);
            this.Controls.Add(this.txtEmailConfirmNumber2);
            this.Controls.Add(this.txtEmailConfirmNumber1);
            this.Controls.Add(this.btn_Buttons);
            this.Controls.Add(this.labelCodeValidityPeriod);
            this.Controls.Add(this.labelTitle);
            this.Controls.Add(this.pictureBoxConfirmScreenMailMiddleWhite);
            this.Controls.Add(this.pictureBoxConfirmScreenPasswordMiddleDark);
            this.Controls.Add(this.pictureBoxConfirmScreenPasswordMiddleWhite);
            this.Controls.Add(this.pictureBoxConfirmScreenMailMiddleDark);
            this.Controls.Add(this.btn_ConfirmMail);
            this.Controls.Add(this.btn_ConfirmPassword);
            this.FormBorderEffect = DevExpress.XtraEditors.FormBorderEffect.Shadow;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.IconOptions.Image = global::HastaneBilgiYonetimSistemi_HBYS_NET_Framework.Properties.Resources.check_mail;
            this.MaximizeBox = false;
            this.Name = "ConfirmScreenForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "E-Posta Doğrulama";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ConfirmScreenForm_FormClosing);
            this.Load += new System.EventHandler(this.ConfirmScreenForm_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ConfirmScreen_KeyDown);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenMailMiddleWhite)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenMailMiddleDark)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenPasswordMiddleWhite)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxConfirmScreenPasswordMiddleDark)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBoxConfirmScreenMailMiddleWhite;
        private System.Windows.Forms.PictureBox pictureBoxConfirmScreenMailMiddleDark;
        private System.Windows.Forms.PictureBox pictureBoxConfirmScreenPasswordMiddleWhite;
        private System.Windows.Forms.PictureBox pictureBoxConfirmScreenPasswordMiddleDark;
        private System.Windows.Forms.Label labelTitle;
        private System.Windows.Forms.Label labelCodeValidityPeriod;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Buttons;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber1;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber2;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber3;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber4;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber5;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmailConfirmNumber6;
        private System.Windows.Forms.Label labelRepeatWantToCode;
        private System.Windows.Forms.Label labelRepeatCodeWaitingTime;
        private System.Windows.Forms.Label labelWrongCode;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ConfirmPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ConfirmMail;
    }
}